### ISSUE TITLE
Puppeteer error: Content Security Policy Violation

### ISSUE THREAD

**Issue by caraya** [filamentgroup/glyphhanger#52]
I tried to run Glyphhanger against a local file and it reports an error with Puppeteer and CSP. 

I ran glyphanger in debug mode and got the following stack trace. 

```
$ DEBUG=glyphhanger* glyphhanger ./index.html
  glyphhanger WebServer.isValidUrl('./index.html') +0ms
  glyphhanger Creating static server +2ms
  glyphhanger:webserver Web server started on 8093 for /Users/carlos/.nvm/versions/node/v8.11.3/lib/node_modules/glyphhanger. +0ms
  glyphhanger:webserver Transforming './index.html' to new URL 'http://localhost:8093/index.html' +1ms
  glyphhanger requesting: 'http://localhost:8093/index.html' +4ms
  glyphhanger:nodes (headless browser console): 'Refused to execute inline script because it violates the following Content Security Policy directive: "default-src \'self\'". Either the \'unsafe-inline\' keyword, a hash (\'sha256-QIoS2+QGXYyRXljAI0X70v5nZ8BdWB6PKs3zkOGGqCA=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'script-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n' +0ms
(node:18512) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Event
    at ExecutionContext.evaluateHandle (/Users/carlos/.nvm/versions/node/v8.11.3/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/ExecutionContext.js:98:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

If I run the command against a gully qualified URL then it works.

**Comment by zachleat** [comment]
HMM @caraya: are there any CSP `<meta>` tags in that `index.html` file? Can you share what’s in it?

**Comment by caraya** [comment]
No, there are no CSP meta tags. 

The file is in Github: [https://github.com/caraya/grid-experiments/blob/master/index.html]( https://github.com/caraya/grid-experiments/blob/master/index.html)

However, if I run it against localhost:5000/ it works on the same file.

**Comment by zachleat** [comment]
I’m not sure why a CSP header would be specified? We’re using `serve-static` for local files. `serve-static` is used when the argument is not a valid URL: e.g. `index.html`.

After a little digging in the `serve-static` repo it looks like they may specify a CSP? Not sure https://github.com/expressjs/serve-static/issues/82 which points to: 
https://github.com/expressjs/serve-static/commit/9484ce6198543093ec38f679c2bd8e5b84885fbb

**Comment by zachleat** [comment]
Anyway, I went down a CSP rabbit hole of trying to override the Content-Security-Policy header in `serve-static` and add a `nonce` to our injected script tags and then I found out that Puppeteer has an option to bypass CSP so I’ll just ship that instead. A little bit wary to do this without being able to repro the issue but I think it’ll be okay here.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetbypasscspenabled

This change will be included with 3.1.0.

**Comment by caraya** [comment]
I will test it when available.

**Comment by caraya** [comment]
this is the error I get now when running 3.0.3 in MacOS 10.14

```
~/code/grid-experiments on master*
$ glyphhanger index.html
(node:3193) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Event
    at ExecutionContext.evaluateHandle (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/ExecutionContext.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/helper.js:144:27)
    at Frame.addScriptTag (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/FrameManager.js:587:29)
  -- ASYNC --
    at Frame.<anonymous> (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.addScriptTag (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/Page.js:387:29)
    at Page.<anonymous> (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/helper.js:145:23)
    at GlyphHanger._fetchUrl (/Users/carlos/.nvm/versions/node/v10.13.0/lib/node_modules/glyphhanger/src/GlyphHanger.js:135:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zachleat** [comment]
v3.1.0 is out now—can you confirm that it’s fixed @caraya?  Thanks!

**Comment by caraya** [comment]
tested it with 3.1.0 and it works successfully. Thanks for taking the time to look into this.
