### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by egeesin** [filamentgroup/glyphhanger#55]
Hello,

My problem is probably about the command itself.  Whatever I write, I always get this output:

```
/Users/ege/.nvm/versions/node/v6.10.2/lib/node_modules/glyphhanger/cmd.js:73
	(async function() {
	       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

I couldn't find similar issues relevant to this. Is this something about my side?

**Comment by sadokx** [comment]
Looks like you have a problem with node.js. Try uninstalling and reinstalling node on your computer.

https://nodejs.org/en/
