### ISSUE TITLE
Nested paths in the parameter

### ISSUE THREAD

**Issue by monochromer** [filamentgroup/glyphhanger#63]
If i use `glyphhanger ./index.html `, then all is well. But if i use `glyphhanger ./src/index.html                                                                                  `, I get an error `GlyphHanger Fetch Error:  Error: Evaluation failed: TypeError: CharacterSet is not a constructor`

```
GlyphHanger Fetch Error:  Error: Evaluation failed: TypeError: CharacterSet is not a constructor
    at new GH (<PROJECT_PATH>/node_modules/glyphhanger/src/glyphhanger-script.js:12:20)
    at __puppeteer_evaluation_script__:11:17
    at ExecutionContext.evaluateHandle (<PROJECT_PATH>/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (<PROJECT_PATH>/node_modules/puppeteer/lib/helper.js:108:27)
    at ExecutionContext.evaluate (<PROJECT_PATH>/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (<PROJECT_PATH>/node_modules/puppeteer/lib/helper.js:109:23)
    at DOMWorld.evaluate (<PROJECT_PATH>/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (<PROJECT_PATH>/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.evaluate (<PROJECT_PATH>/node_modules/puppeteer/lib/Page.js:815:43)
    at Page.<anonymous> (<PROJECT_PATH>/node_modules/puppeteer/lib/helper.js:109:23)
    at PuppeteerEnvironment.getResults (<PROJECT_PATH>/node_modules/glyphhanger/src/GlyphHangerEnvironment.js:156:15)
    at GlyphHangerEnvironment.getResults (<PROJECT_PATH>/node_modules/glyphhanger/src/GlyphHangerEnvironment.js:213:25)
    at GlyphHanger._fetchUrl (<PROJECT_PATH>/node_modules/glyphhanger/src/GlyphHanger.js:131:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by eladmizrahi** [comment]
I Get the same error while trying to fetch from a url.
