### ISSUE TITLE
Installation currently not possible

### ISSUE THREAD

**Issue by mekkablue** [filamentgroup/glyphhanger#73]
Related to #66 and #70 

But it seems to have become more serious. Currently, you cannot install glyphhanger on macOS (10.14.6) because of puppeteer:

```
$ sudo npm install -g glyphhanger
/usr/local/bin/glyphhanger -> /usr/local/lib/node_modules/glyphhanger/cmd.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/glyphhanger/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/glyphhanger/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/glyphhanger/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/glyphhanger/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rainerscheichelbauer/.npm/_logs/2019-12-11T10_08_49_396Z-debug.log
```

**Comment by mekkablue** [comment]
[In the puppeteer repo](https://github.com/puppeteer/puppeteer/issues/2173#issuecomment-399745457), this was brought up as a possible solution: 

```
sudo npm install -g puppeteer --unsafe-perm=true --allow-root
```

I suggest to update the installation instructions accordingly.

**Comment by DanielRuf** [comment]
`sudo` should never be used. Apple has increased the security so to specific paths can not be written by default. It should work with nvm, nodenv and so on.

There are better solutions like chowning the needed paths.
